### ISSUE TITLE
Deactivating an unconfirmed user: "http: panic serving 172.20.xxx.yyy:13190: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by 3oris** [1Password/scim-examples#87]
This should obviously be addressed (op-scim Version 1.3.0-2):
```
[LOG] [1.3.0] 2020/03/03 08:31:49 (INFO) Handling PATCH: /Users/H2LKSSXXXXXXXXXXXXXXXXY754
[LOG] [1.3.0] 2020/03/03 08:31:49 (INFO) found singleOperation with type Replace, path active
[LOG] [1.3.0] 2020/03/03 08:31:49 (INFO) found singleOperation with type Replace, path emails[type eq "work"].value
[LOG] [1.3.0] 2020/03/03 08:31:49 (INFO) applying 2 field operations to user H2LKSSXXXXXXXXXXXXXXXXY754
[LOG] [1.3.0] 2020/03/03 08:31:49 (INFO) ApplyUserFieldOperation applying op.Type "Replace" for op.Path "active" to user xxxxxxx@example.com
[LOG] [1.3.0] 2020/03/03 08:31:49 (WARN) deactivateUser cannot suspended user from state (3), user will be deleted
[LOG] [1.3.0] 2020/03/03 08:31:49 (INFO) deactivateUser deleted user xxxxxxx@example.com
2020/03/03 08:31:49 http: panic serving 172.20.xxx.yyy:13190: runtime error: invalid memory address or nil pointer dereference
goroutine 610562 [running]:
net/http.(*conn).serve.func1(0xc000204820)
        /usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x8fd6a0, 0xdc1910)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
go.1password.io/op-scim/action.ApplyUserFieldOperation(0xc0000a2740, 0xc0000fe280, 0x0, 0xc0000ac410, 0x7, 0xc00035b6e0, 0x1c, 0x8cee80, 0xc000376430, 0x0, ...)
        /go/src/go.1password.io/op-scim/action/users.go:257 +0x87
go.1password.io/op-scim/action.ApplyUserFieldOperations(0xc0000a2740, 0xc0000fe280, 0x0, 0xc000134090, 0x2, 0x2, 0xc0000a2da0, 0x0, 0x7ffac33876d0)
        /go/src/go.1password.io/op-scim/action/users.go:233 +0x170
go.1password.io/op-scim/handler.PatchUserHandler.func1(0xa5f120, 0xc0003fc000, 0xc0001f0600)
        /go/src/go.1password.io/op-scim/handler/users.go:151 +0x276
go.1password.io/op-scim/handler.AuthWrap.func1(0xa5f120, 0xc0003fc000, 0xc0001f0600)
        /go/src/go.1password.io/op-scim/handler/root.go:87 +0x23b
go.1password.io/op-scim/handler.HealthWrap.func1(0xa5f120, 0xc0003fc000, 0xc0001f0600)
        /go/src/go.1password.io/op-scim/handler/root.go:133 +0x6f
go.1password.io/op-scim/handler.LogWrap.func1(0xa5f120, 0xc0003fc000, 0xc0001f0600)
        /go/src/go.1password.io/op-scim/handler/root.go:125 +0x151
net/http.HandlerFunc.ServeHTTP(0xc0001966e0, 0xa5f120, 0xc0003fc000, 0xc0001f0600)
        /usr/local/go/src/net/http/server.go:2007 +0x44
go.1password.io/op-scim/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00017a000, 0xa5f120, 0xc0003fc000, 0xc0001f0300)
        /go/src/go.1password.io/op-scim/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
net/http.serverHandler.ServeHTTP(0xc0001a60e0, 0xa5f120, 0xc0003fc000, 0xc0001f0300)
        /usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc000204820, 0xa601e0, 0xc00016a280)
        /usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2928 +0x384
```

**Comment by cohix** [comment]
Thanks for reporting. We are aware of this issue and it will be addressed in the next release.
